### PR TITLE
Adding Continus Integration

### PR DESCRIPTION
**Pull request by drts01**
- Add Tox config for testing
- Add Travis config for CI
- Enable Pylint extentions
- Update setup.cfg

### CODE REVIEW

**Comment by LeStarch** [comment]
@CMeza99 it looks like you are running tests on Python 3.7.  We need to run tests on the stock 18.04 python 3.5.

Also, what do these plugins do? pylint.extensions.mccabe,pylint.extensions.redefined_variable_type

**Review by LeStarch — CHANGES_REQUESTED** [review]
Support Python 3.5 baseline.

**Comment by drts01** [comment]
As soon as we have unit tests, they will run in all the versions listed in the tox.ini and setup.cfg. We should ensure future proofing.

- https://github.com/socallinuxexpo/hdmi_matrix_control/pull/6/files#diff-380c6a8ebbbce17d55d50ef17d3cf906L20
- https://github.com/socallinuxexpo/hdmi_matrix_control/pull/6/files#diff-380c6a8ebbbce17d55d50ef17d3cf906L20

Linting in Py37 should be fine, but the unit tests definitely need to be checked against Py35. And Black is unavailable for Py35, so the check has to be done in at least Py36.

Mccabe is a code complexity checker, it defaults to something really high, http://pylint.pycqa.org/en/latest/technical_reference/extensions.html?highlight=extensions#pylint-extensions-mccabe.
The var reuse extension for pyline, catches if a var is being reused, http://pylint.pycqa.org/en/latest/technical_reference/extensions.html?highlight=extensions#pylint-extensions-redefined-variable-type.

**Comment by drts01** [comment]
I concede on the linting should be done with 3.5.

Tangentially, I think we should look at decoupling the application from the O.S., especially the Python interpreter.

**Comment by LeStarch** [comment]
I agree we should, but we won't ever win the battle of not using the system Python3 so it is a moot point.

**Review by LeStarch — APPROVED** [review]
LGTM.

**Comment by drts01** [comment]
(This is just a note for future discussion)

Why is using the system Python a battle? Rather than a conversion of changing the installed interpreter, It is more of a discussion about packaging, distribution, and/or deployment. But if we did want to change the installed interpreters @mproctor13 has stated he is not 100% oppose, but it it clearly not his preference.

Decoupling from the system interpreter a lots us more freedoms, making future development easier. Besides being able to take advantage a newer features, i.e. type-hinting, data-classes, etc., we are able to make changes to the version of Python we support when is convenient for us. Being tied to the system forces us to update when the distro wants to change and we have less ability to do it piecemeal. Also, we will have to make less compromises to maintain compatibility (an extreme example, any code that trys to be compatible w/ Py2 and Py3).

Well, this is not something tackle for SCaLE 17x. Nor is the proper thread :smile: . But is a topic that should be revisited.

**Pull request merged**
